[11/Apr/2016 20:20:39] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:20:39] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:20:55] WARNING [django.request:170] Not Found: /favicon.ico
[11/Apr/2016 20:23:37] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:23:37] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:25:42] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8\gigm8app\views.py", line 13, in index
    template = loader.get_template('templates/index.html')
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: templates/index.html
[11/Apr/2016 20:26:15] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:26:15] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:26:15] WARNING [django.request:170] Not Found: /css/ionicons.min.css
[11/Apr/2016 20:26:15] WARNING [django.request:170] Not Found: /css/animate.css
[11/Apr/2016 20:26:15] WARNING [django.request:170] Not Found: /css/bootstrap.min.css
[11/Apr/2016 20:26:15] WARNING [django.request:170] Not Found: /css/owl.carousel.css
[11/Apr/2016 20:26:15] WARNING [django.request:170] Not Found: /css/slider.css
[11/Apr/2016 20:26:15] WARNING [django.request:170] Not Found: /css/owl.theme.css
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /css/jquery.fancybox.css
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /css/main.css
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /css/responsive.css
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 20:26:16] WARNING [django.request:170] Not Found: /images/favicon.png
[11/Apr/2016 20:28:54] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:28:54] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/slider.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/bootstrap.min.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/owl.theme.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/animate.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/ionicons.min.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/owl.carousel.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/jquery.fancybox.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/main.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /css/responsive.css
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:29:31] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:29:32] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:29:32] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:29:32] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:29:32] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:29:32] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:29:32] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 20:31:43] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:31:43] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:31:43] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:31:43] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:31:43] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:31:43] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:31:43] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:31:43] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 20:31:45] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:31:45] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:31:45] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:31:45] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:31:45] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:31:45] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:31:45] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:31:45] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 20:37:59] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:37:59] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:38:04] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:38:04] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:38:04] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:38:04] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:38:04] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:38:04] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:38:04] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:38:04] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 20:38:07] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:38:07] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:38:07] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:38:07] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:38:07] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:38:07] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:38:07] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:38:07] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 20:38:44] WARNING [django.request:170] Not Found: /css/bootstrap.min.css
[11/Apr/2016 20:38:52] WARNING [django.request:170] Not Found: /static
[11/Apr/2016 20:47:51] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:47:51] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:48:45] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:48:45] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:48:45] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:48:45] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:48:45] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:48:45] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:48:45] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:48:45] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 20:48:50] WARNING [django.request:170] Not Found: /events.html
[11/Apr/2016 20:49:08] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:49:08] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:49:50] WARNING [django.request:170] Not Found: /events
[11/Apr/2016 20:49:59] WARNING [django.request:170] Not Found: /events
[11/Apr/2016 20:50:07] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:50:07] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:50:11] WARNING [django.request:170] Not Found: /events
[11/Apr/2016 20:50:18] WARNING [django.request:170] Not Found: /index
[11/Apr/2016 20:50:23] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:50:23] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:50:23] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:50:23] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:50:23] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:50:23] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:50:23] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:50:23] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 20:53:05] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 20:53:05] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 20:53:17] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 20:53:17] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 20:53:17] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 20:53:17] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 20:53:17] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 20:53:17] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 20:53:17] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 20:53:17] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 21:00:38] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 21:00:38] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 21:00:45] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 21:00:45] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 21:00:48] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 21:00:48] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 21:00:48] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 21:00:48] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 21:00:48] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 21:00:48] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 21:00:48] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 21:00:48] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 21:00:52] WARNING [django.request:170] Not Found: /static
[11/Apr/2016 21:01:00] WARNING [django.request:170] Not Found: /events
[11/Apr/2016 21:02:54] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 21:02:54] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:13:24] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:13:24] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:14:01] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:14:01] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:14:38] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:14:38] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:14:43] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:14:43] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:15:02] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:15:02] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:18:06] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:18:06] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:18:36] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\OpenData\Coursework2\gigm8\gigm8\urls.py", line 35, in <module>
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT, 'show_indexes' : True}),
TypeError: 'list' object is not callable
[11/Apr/2016 22:18:55] ERROR [django.request:256] Internal Server Error: /static
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 108, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 646, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 521, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\OpenData\Coursework2\gigm8\gigm8\urls.py", line 35, in <module>
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT, 'show_indexes' : True}),
TypeError: 'list' object is not callable
[11/Apr/2016 22:21:22] ERROR [django.request:256] Internal Server Error: /static
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 108, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 646, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 521, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\OpenData\Coursework2\gigm8\gigm8\urls.py", line 35, in <module>
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT, 'show_indexes' : True})
TypeError: 'list' object is not callable
[11/Apr/2016 22:30:12] ERROR [django.request:256] Internal Server Error: /static
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 108, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 646, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 521, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\OpenData\Coursework2\gigm8\gigm8\urls.py", line 34, in <module>
    urlpatterns += patterns('',
NameError: name 'patterns' is not defined
[11/Apr/2016 22:30:15] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\OpenData\Coursework2\gigm8\gigm8\urls.py", line 34, in <module>
    urlpatterns += patterns('',
NameError: name 'patterns' is not defined
[11/Apr/2016 22:31:17] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 22:31:17] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 22:31:17] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 22:31:17] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 22:31:17] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 22:31:17] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 22:31:17] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 22:31:17] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 22:32:02] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:32:02] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:32:44] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 22:32:52] WARNING [django.request:170] Not Found: /events.html
[11/Apr/2016 22:37:17] WARNING [django.request:170] Not Found: /evnts
[11/Apr/2016 22:40:00] WARNING [django.request:170] Not Found: /index.html
[11/Apr/2016 22:40:14] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:40:14] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:40:23] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:40:23] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/bootstrap.min.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/ionicons.min.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/animate.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/slider.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/owl.carousel.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/owl.theme.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/jquery.fancybox.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/main.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /css/responsive.css
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 22:44:51] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/bootstrap.min.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/ionicons.min.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/animate.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/slider.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/owl.carousel.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/owl.theme.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/jquery.fancybox.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/main.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /css/responsive.css
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /js/vendor/modernizr-2.6.2.min.js
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /js/owl.carousel.min.js
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /js/bootstrap.min.js
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /js/wow.min.js
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /js/slider.js
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /js/jquery.fancybox.js
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /js/main.js
[11/Apr/2016 22:44:53] WARNING [django.request:170] Not Found: /images/logo.png
[11/Apr/2016 22:50:19] WARNING [django.request:170] Not Found: /index
[11/Apr/2016 22:50:30] WARNING [django.request:170] Not Found: /index
[11/Apr/2016 22:50:58] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 22:50:58] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[11/Apr/2016 23:00:24] DEBUG [django.db.backends:89] (0.000) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[11/Apr/2016 23:00:24] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/Apr/2016 11:57:05] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 11:57:05] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 11:57:09] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 11:57:09] DEBUG [django.db.backends:89] (0.002) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 11:57:16] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 11:57:16] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 11:57:28] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 11:57:28] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:02:22] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:02:22] DEBUG [django.db.backends:89] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:03:48] DEBUG [django.db.backends:89] (0.005) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:03:48] DEBUG [django.db.backends:89] (0.002) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:05:19] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:05:19] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:05:19] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:05:19] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:06:24] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:06:24] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:06:24] DEBUG [django.db.backends:89] (0.003) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:06:24] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:07:10] DEBUG [django.db.backends:89] (0.004) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:07:10] DEBUG [django.db.backends:89] (0.002) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:07:58] DEBUG [django.db.backends:89] (0.008) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:07:58] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:08:10] WARNING [django.request:182] Not Found: /static
[12/Apr/2016 12:08:10] DEBUG [django.template:927] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\template\base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[12/Apr/2016 12:08:35] DEBUG [django.db.backends:89] (0.003) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:08:35] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:13:15] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:13:15] DEBUG [django.db.backends:89] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:13:28] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:13:28] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:13:51] DEBUG [django.db.backends:89] (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:13:51] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:14:22] DEBUG [django.db.backends:89] (0.004) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:14:22] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:14:37] DEBUG [django.db.backends:89] (0.003) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[12/Apr/2016 12:14:37] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[12/Apr/2016 12:15:08] WARNING [django.request:182] Not Found: /css/slider.css
[12/Apr/2016 12:15:09] DEBUG [django.template:927] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\template\base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[12/Apr/2016 12:53:46] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/Apr/2016 12:53:46] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/Apr/2016 12:54:15] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 9, in index
    template = loader.get_template('index.html')
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
[12/Apr/2016 12:57:38] WARNING [django.request:170] Not Found: /images/logo.png
[12/Apr/2016 12:58:16] WARNING [django.request:170] Not Found: / /static/logo.png
[12/Apr/2016 12:58:40] WARNING [django.request:170] Not Found: /'../'/static/logo.png
[12/Apr/2016 13:00:14] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/Apr/2016 13:00:14] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/Apr/2016 13:01:47] ERROR [django.request:256] Internal Server Error: /index
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 9, in index
    template = loader.get_template('index.html')
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
[12/Apr/2016 13:01:50] ERROR [django.request:256] Internal Server Error: /index
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 9, in index
    template = loader.get_template('index.html')
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/slider.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/ionicons.min.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/animate.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/owl.theme.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/owl.carousel.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/jquery.fancybox.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/main.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/css/responsive.css
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/js/vendor/modernizr-2.6.2.min.js
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/js/owl.carousel.min.js
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.js
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/js/wow.min.js
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/js/slider.js
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/js/jquery.fancybox.js
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/js/main.js
[12/Apr/2016 13:03:03] WARNING [django.request:170] Not Found: /static/images/logo.png
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/ionicons.min.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/animate.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/slider.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/owl.carousel.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/owl.theme.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/jquery.fancybox.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/main.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/css/responsive.css
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/js/vendor/modernizr-2.6.2.min.js
[12/Apr/2016 13:03:07] WARNING [django.request:170] Not Found: /static/js/owl.carousel.min.js
[12/Apr/2016 13:03:08] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.js
[12/Apr/2016 13:03:08] WARNING [django.request:170] Not Found: /static/js/wow.min.js
[12/Apr/2016 13:03:08] WARNING [django.request:170] Not Found: /static/js/slider.js
[12/Apr/2016 13:03:08] WARNING [django.request:170] Not Found: /static/js/jquery.fancybox.js
[12/Apr/2016 13:03:08] WARNING [django.request:170] Not Found: /static/js/main.js
[12/Apr/2016 13:03:08] WARNING [django.request:170] Not Found: /static/images/logo.png
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/slider.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/animate.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/ionicons.min.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/owl.carousel.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/owl.theme.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/jquery.fancybox.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/main.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/css/responsive.css
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/js/vendor/modernizr-2.6.2.min.js
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/js/owl.carousel.min.js
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.js
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/js/wow.min.js
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/js/slider.js
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/js/jquery.fancybox.js
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/js/main.js
[12/Apr/2016 13:03:09] WARNING [django.request:170] Not Found: /static/images/logo.png
[12/Apr/2016 13:04:14] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x04C278B0>.
[12/Apr/2016 13:04:24] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x04C278B0>.
[12/Apr/2016 13:04:26] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x04C278B0>.
[12/Apr/2016 13:04:28] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x04C278B0>.
[12/Apr/2016 13:05:43] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x04C455B0>.
[12/Apr/2016 13:05:50] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x04C455B0>.
[12/Apr/2016 13:06:16] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/Apr/2016 13:06:16] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/Apr/2016 13:17:22] ERROR [django.request:256] Internal Server Error: /index.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x050966D0>.
[12/Apr/2016 13:17:44] ERROR [django.request:256] Internal Server Error: /index.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x04B996D0>.
[12/Apr/2016 13:20:26] ERROR [django.request:256] Internal Server Error: /index.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x049BB550>.
[12/Apr/2016 13:20:35] ERROR [django.request:256] Internal Server Error: /index.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x049BB550>.
[12/Apr/2016 13:20:38] ERROR [django.request:256] Internal Server Error: /index.html
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\OpenData\Coursework2\gigm8Heroku\gigm8\gigm8app\views.py", line 10, in index
    return HttpResponse(template.render(request))
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/logo.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x049BB550>.
[12/Apr/2016 13:20:47] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/Apr/2016 13:20:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/Apr/2016 14:45:37] DEBUG [django.db.backends:89] (0.003) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/Apr/2016 14:45:37] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
